name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10

permissions:
  contents: read

jobs:
  publish-binary:
    name: Publish binary
    permissions: 
      contents: write
      id-token: write
    runs-on: ${{ matrix.build.os }}
    strategy:
      fail-fast: false
      matrix:
        build:
          - {
              NAME: linux-x64-gnu,
              OS: ubuntu-22.04,
              TARGET: x86_64-unknown-linux-gnu,
            }
          - {
              NAME: linux-arm64-gnu,
              OS: ubuntu-22.04,
              TARGET: aarch64-unknown-linux-gnu,
            }
          - {
              NAME: linux-x64-musl,
              OS: ubuntu-22.04,
              TARGET: x86_64-unknown-linux-musl,
            }
          - {
              NAME: linux-arm64-musl,
              OS: ubuntu-22.04,
              TARGET: aarch64-unknown-linux-musl,
            }
          # - {
          #     NAME: win32-x64-msvc,
          #     OS: windows-2022,
          #     TARGET: x86_64-pc-windows-msvc,
          #   }
          # - {
          #     NAME: win32-arm64-msvc,
          #     OS: windows-2022,
          #     TARGET: aarch64-pc-windows-msvc,
          #   }
          - {
              NAME: darwin-x64,
              OS: macos-12,
              TARGET: x86_64-apple-darwin,
            }
          - {
              NAME: darwin-arm64,
              OS: macos-12,
              TARGET: aarch64-apple-darwin,
            }
    env:
      NAME: ${{ matrix.build.NAME }}
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2
        with:
          use-policy-store: true
          api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
      - name: Setup mise
        uses: step-security/mise-action@6e96d2ffbc65c037f23c78818f2a339d6cf830f7 # v4.2.4
        with:
          version: '2026.8.12'
      - name: Set the release version
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
      - name: Install dependencies
        shell: bash
        run: |
          if [[ "${{ matrix.build.NAME }}" = *"-musl" ]]; then
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends \
              --allow-unauthenticated musl-tools
          fi
      - uses: step-security/rust-cache@851174d9a2fdc03e0896e02844dcc61d81dd7851 # v2.9.1
        with:
          shared-key: ${{ matrix.build.TARGET }}-build
      - name: Install Rust toolchain
        uses: step-security/actions-rs-toolchain@40a2f87e50bed6faa2d050e99810b226b75d8c8a # v1.0.7
        with:
          toolchain: stable
          target: ${{ matrix.build.TARGET }}
          override: true
      - name: Build (linux/macos)
        if: matrix.build.OS != 'windows-2022'
        uses: step-security/actions-rs-cargo@34f23e8d4bb3618bc5485c3341f2bf88024fc4dc # v1.0.1
        with:
          use-cross: true
          command: build
          args: --release --locked --target ${{ matrix.build.TARGET }}
      - name: Build (windows)
        if: matrix.build.OS == 'windows-2022'
        uses: step-security/actions-rs-cargo@34f23e8d4bb3618bc5485c3341f2bf88024fc4dc # v1.0.1
        with:
          command: build
          args: --release --locked --target ${{ matrix.build.TARGET }} # --no-default-features
      - name: Prepare release assets
        shell: bash
        run: |
          mkdir -p packages/ts-gettext-extractor-${{ env.NAME }}/bin/
          bin=ts-gettext-extractor
          if [ "${{ matrix.build.OS }}" = "windows-2022" ]; then
            bin="${bin}.exe"
          fi
          cp "target/${{ matrix.build.TARGET }}/release/${bin}" packages/ts-gettext-extractor-${{ env.NAME }}/bin/
      - name: Create release artifacts
        shell: bash
        run: |
          cd packages
          if [ "${{ matrix.build.OS }}" = "windows-2022" ]; then
            7z a -tzip "../ts-gettext-extractor-${{ env.NAME }}-${{ env.RELEASE_VERSION }}.zip" \
            ts-gettext-extractor-${{ env.NAME }}/
          else
            tar -czvf ../ts-gettext-extractor-${{ env.NAME }}-${{ env.RELEASE_VERSION }}.tar.gz \
              ts-gettext-extractor-${{ env.NAME }}/
            shasum -a 512 ../ts-gettext-extractor-${{ env.NAME }}-${{ env.RELEASE_VERSION }}.tar.gz \
              > ../ts-gettext-extractor-${{ env.NAME }}-${{ env.RELEASE_VERSION }}.tar.gz.sha512
          fi
      - name: Publish to GitHub
        if: ${{ !contains(github.ref, '-') }}
        uses: step-security/upload-release-action@ecbc6042326f3a6f5a8c1c1202c4fa1b244db249 # v2.11.4
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ts-gettext-extractor-${{ env.NAME }}-${{ env.RELEASE_VERSION }}*
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
          release_name: "Release v${{ env.RELEASE_VERSION }}"
      - name: Publish to GitHub (pre-release)
        if: ${{ contains(github.ref, '-') }}
        uses: step-security/upload-release-action@ecbc6042326f3a6f5a8c1c1202c4fa1b244db249 # v2.11.4
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ts-gettext-extractor-${{ env.NAME }}-${{ env.RELEASE_VERSION }}*
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
          release_name: "Pre-release v${{ env.RELEASE_VERSION }}"
          prerelease: true
      - run: corepack enable
      - name: Configure npm registry
        run: |
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" >> ~/.npmrc
      - name: Publish to NPM
        run: |
          cd packages/ts-gettext-extractor-${{ env.NAME }}/
          if [ ${{ contains(github.ref, '-') }} = "true" ]; then
            npm publish --provenance --access public --tag rc
          else
            npm publish --provenance --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-main-package:
    needs: publish-binary
    permissions: 
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2
        with:
          use-policy-store: true
          api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
      - name: Setup mise
        uses: step-security/mise-action@6e96d2ffbc65c037f23c78818f2a339d6cf830f7 # v4.2.4
        with:
          version: '2026.8.12'
      - run: corepack enable
      - name: Configure npm registry
        run: |
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" >> ~/.npmrc
      - run: |
          cp README.md packages/ts-gettext-extractor/
      - name: Publish to NPM
        run: |
          cd packages/ts-gettext-extractor
          if [ ${{ contains(github.ref, '-') }} = "true" ]; then
            npm publish --provenance --access public --tag rc
          else
            npm publish --provenance --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  
  publish-crate:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2
        with:
          use-policy-store: true
          api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v3
      - uses: step-security/rust-cache@851174d9a2fdc03e0896e02844dcc61d81dd7851 # v2.9.1
      - run: cargo publish --token ${{secrets.CARGO_TOKEN}}
